In [6]:
import numpy as np
import pandas as pd
import seaborn as sns

data = sns.load_dataset('iris')
df = pd.DataFrame(data)
df['species'].nunique()

###----------logistic regression for multiclass
# df.isnull().sum()
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [21]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['species'] = encoder.fit_transform(df['species'])
# df.drop(columns=['sepal_width','petal_width'],inplace=True)
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X

     sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=1000)

clf.fit(X_train,Y_train)
y_p = clf.predict(X_test) 

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_p)

1.0

In [26]:
###----- confusion matrix
from sklearn.metrics import confusion_matrix,precision_score,recall_score
pd.DataFrame(confusion_matrix(Y_test,y_p))
test = np.array([[5.3,1.9]])
clf.predict_proba(test)

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[8.83719201e-01, 1.16276423e-01, 4.37545294e-06]])